POST http://127.0.0.1:8080/oauth2/authorization/service-client

###
POST http://127.0.0.1:8091/oauth2/authorize?response_type=code&client_id=service-client&scope=openid%20profile%20read%20write&state=cJFqzxeFrJzzBvM7CYWGpaEotkLdprhSesHe7PkaZjo%3D&redirect_uri=http://127.0.0.1:8080/authorized&nonce=yRSmCkcnY_r9W8of0kOiHOX32x9J1RVYGrhf3QpUyK4

###

POST http://127.0.0.1:8091/login
Content-Type: application/x-www-form-urlencoded

username=user&password=1234

###
POST http://127.0.0.1:8091
Cookie: JSESSIONID=AB0CF393836C94F629B8D97DED9F6C1E;

###

get https://localhost:8443/messages

###
# @name session
POST http://127.0.0.1:9000/oauth2/authorization/webapp

###

POST http://127.0.0.1:9000/login
Content-Type: application/x-www-form-urlencoded

username=user1&password=1

###
GET http://127.0.0.1:9000/.well-known/oauth-authorization-server


###
POST http://127.0.0.1:8091/oauth2/authorization/public-client

###
# @name session
POST http://127.0.0.1:8091/oauth2/authorization/service-client

###
@JSESSIONID = {{session.response.headers.Set-Cookie.JSESSIONID}}

POST http://127.0.0.1:8091/login
Content-Type: application/x-www-form-urlencoded

username=user1&password=1

###
POST http://127.0.0.1:8091/oauth2/authorization/public-client

###
POST http://127.0.0.1:8091/login
Content-Type: application/x-www-form-urlencoded

username=user1&password=1
###

post http://127.0.0.1:8091/oauth2/authorization/public-client?continue

